### ISSUE TITLE
First launch fails with python traceback due to missing %localappdata%\tracs\tracs folder

### ISSUE THREAD

**Issue by TheStalwart** [fortysix2ahead/tracs#221]
I've been following [quick start guide](https://tracs.readthedocs.io/en/latest/start/) on a Windows 11 system and there is an issue at `tracs version` step.

```
(venv) PS C:\Users\stlwr\Code\tracs> tracs list
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\stlwr\Code\tracs\venv\Scripts\tracs.exe\__main__.py", line 7, in <module>
  File "C:\Users\stlwr\Code\tracs\tracs\__main__.py", line 9, in main
    main_cli()
  File "C:\Users\stlwr\Code\tracs\tracs\cli.py", line 354, in main
    cli()  # trigger cli
    ^^^^^
  File "C:\Users\stlwr\Code\tracs\venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stlwr\Code\tracs\venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\stlwr\Code\tracs\venv\Lib\site-packages\click\core.py", line 1685, in invoke
    super().invoke(ctx)
  File "C:\Users\stlwr\Code\tracs\venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stlwr\Code\tracs\venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stlwr\Code\tracs\venv\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stlwr\Code\tracs\tracs\cli.py", line 50, in cli
    APPLICATION_INSTANCE = Application.instance(
                           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stlwr\Code\tracs\tracs\application.py", line 38, in instance
    cls._instance = Application.__new__( cls, *args, **kwargs )
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stlwr\Code\tracs\tracs\application.py", line 48, in __new__
    instance.__setup__( **kwargs )
  File "C:\Users\stlwr\Code\tracs\tracs\application.py", line 79, in __setup__
    self._ctx = ApplicationContext( *args, **kwargs )
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stlwr\Code\tracs\tracs\config.py", line 244, in __init__
    self.__attrs_init__( *args, **kwargs, __kwargs__ = extra_kwargs  )
  File "<attrs generated init tracs.config.ApplicationContext>", line 36, in __attrs_init__
  File "C:\Users\stlwr\Code\tracs\tracs\config.py", line 248, in __attrs_post_init__
    self.__setup_config_fs__()
  File "C:\Users\stlwr\Code\tracs\tracs\config.py", line 151, in __setup_config_fs__
    self.config_fs = OSFS( root_path=user_config_dir( APPNAME ) )
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stlwr\Code\tracs\venv\Lib\site-packages\fs\osfs.py", line 141, in __init__
    raise errors.CreateFailed(message)
fs.errors.CreateFailed: root path 'C:\Users\stlwr\AppData\Local\tracs\tracs' does not exist
```

I worked around the problem by manually creating %localappdata%\tracs\tracs folder

**Comment by fortysix2ahead** [comment]
You're on Windows 11, I'll see if I can get access to a Windows machine to test it ...
