### ISSUE TITLE
Setup fails with accessing dynaconf keys

### ISSUE THREAD

**Issue by fortysix2ahead** [fortysix2ahead/tracs#321]
```
Traceback (most recent call last):
  File "/usr/local/pkgs/tracs/bin/tracs", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/pkgs/tracs/lib/python3.11/site-packages/tracs/__main__.py", line 9, in main
    main_cli()
  File "/usr/local/pkgs/tracs/lib/python3.11/site-packages/tracs/cli.py", line 360, in main
    cli()  # trigger cli
    ^^^^^
  File "/usr/local/pkgs/tracs/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pkgs/tracs/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/pkgs/tracs/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pkgs/tracs/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pkgs/tracs/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pkgs/tracs/lib/python3.11/site-packages/click/decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pkgs/tracs/lib/python3.11/site-packages/tracs/cli.py", line 298, in setup
    setup_application( ctx, services )
  File "/usr/local/pkgs/tracs/lib/python3.11/site-packages/tracs/setup.py", line 66, in setup
    existing_config = ctx.config.plugins[name]
                      ~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/pkgs/tracs/lib/python3.11/site-packages/dynaconf/utils/boxing.py", line 18, in evaluate
    value = f(dynabox, item, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pkgs/tracs/lib/python3.11/site-packages/dynaconf/utils/boxing.py", line 49, in __getitem__
    return super().__getitem__(n_item, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pkgs/tracs/lib/python3.11/site-packages/dynaconf/vendor/box/box.py", line 163, in __getitem__
    raise BoxKeyError(str(E))from _A
dynaconf.vendor.box.exceptions.BoxKeyError: "'tracs.plugins.bikecitizens'"```

**Comment by fortysix2ahead** [comment]
Closed too early ...
