### ISSUE TITLE
Bare metal startup is broken

### ISSUE THREAD

**Issue by fortysix2ahead** [fortysix2ahead/tracs#388]
Some of the directories introduced aren't created automatically on startup. Did not check on this for a long time as this does not happen when having a working dev setup.

**Comment by fortysix2ahead** [comment]
Startup works in PyCharm, but not in terminal:

```
12:10:36 DEBUG    triggered CLI with flags {'configuration': '/config.yaml', 'library': None, 'verbose': None, 'debug': True, 'force': None, 'pretend': None, 'json': None, 'features': []}                                application.py:56
         DEBUG    config fs set to <osfs '/'>                                                                                                                                                                                  config.py:179
Traceback (most recent call last):
  File "/Users/Projects/tracs/venv/python312/lib/python3.12/site-packages/fs/osfs.py", line 334, in makedir
    os.mkdir(sys_path, mode)
OSError: [Errno 30] Read-only file system: b'/db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Projects/tracs/venv/python312/bin/tracs", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/Projects/tracs/tracs/__main__.py", line 9, in main
    main_cli()
  File "/Users/Projects/tracs/tracs/cli.py", line 372, in main
    cli()  # trigger cli
    ^^^^^
  File "/Users/Projects/tracs/venv/python312/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Projects/tracs/venv/python312/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/Projects/tracs/venv/python312/lib/python3.12/site-packages/click/core.py", line 1685, in invoke
    super().invoke(ctx)
  File "/Users/Projects/tracs/venv/python312/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Projects/tracs/venv/python312/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Projects/tracs/venv/python312/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Projects/tracs/tracs/cli.py", line 53, in cli
    APPLICATION_INSTANCE = Application.instance(
                           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Projects/tracs/tracs/application.py", line 37, in instance
    cls._instance = Application.__new__( cls, *args, **kwargs )
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Projects/tracs/tracs/application.py", line 47, in __new__
    instance.__setup__( *args, **kwargs )
  File "/Users/Projects/tracs/tracs/application.py", line 81, in __setup__
    self._ctx = ApplicationContext( __args__=args, __kwargs__=kwargs )
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<attrs generated init tracs.config.ApplicationContext>", line 38, in __init__
  File "/Users/Projects/tracs/tracs/config.py", line 261, in __attrs_post_init__
    self.__setup_library__()
  File "/Users/Projects/tracs/tracs/config.py", line 230, in __setup_library__
    self.db_fs = _subfs( self.lib_fs, DB_DIRNAME )
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Projects/tracs/tracs/config.py", line 534, in _subfs
    parent.makedirs( path, recreate=True )
  File "/Users/Projects/tracs/venv/python312/lib/python3.12/site-packages/fs/base.py", line 1132, in makedirs
    self.makedir(path, permissions=permissions)
  File "/Users/Projects/tracs/venv/python312/lib/python3.12/site-packages/fs/osfs.py", line 332, in makedir
    with convert_os_errors("makedir", path, directory=True):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Projects/tracs/venv/python312/lib/python3.12/site-packages/fs/error_tools.py", line 89, in __exit__
    reraise(fserror, fserror(self._path, exc=exc_value), traceback)
  File "/Users/Projects/tracs/venv/python312/lib/python3.12/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/Users/Projects/tracs/venv/python312/lib/python3.12/site-packages/fs/osfs.py", line 334, in makedir
    os.mkdir(sys_path, mode)
fs.errors.OperationFailed: operation failed, [Errno 30] Read-only file system: b'/db'
```

**Comment by fortysix2ahead** [comment]
Actually it's not broken. In case of a wrong configuration path, the exception above is raised. There should be a proper error message.
